### ISSUE TITLE
Build tensile data in unexpected place

### ISSUE THREAD

**Issue by ProfHill-UCD** [SRP-AM/SRP_AM_Prediction_Challenge#3]
The file at
ResidualStress/CalTask/WAAM Results revBLB.xlsx

provides tension test data at various temperatures from samples cut from a calibration build and a challenge build. That's a useful file but it does not belong in the ResidualStress branch.

Perhaps the file should be relocated here:
Other/BuildTensileData

Or make a new folder for materials
Materials/Build

and then one for Baseplate
Materials/Base

There should also be added a document that shows from where in the builds the samples were extracted. Hopefully Brad has such a document. I think Nick may have developed a report.

**Comment by bachus34** [comment]
Moved files to new Materials directory which now contains the build, baseplate, and wire data. Currently working with Brad to obtain tensile specimen extraction orientations to be included in the documentation.
